[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]

[tool.black]
target-version = ['py38']
line-length = 88
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | _version.py
  )
)
'''


[tool.isort]
profile = "black"
combine_as_imports = true
skip =  ["venv", "benchmarks"]

[tool.setuptools_scm]
write_to = "unyt/_version.py"
version_scheme = "post-release"

[tool.pytest.ini_options]
addopts = "--ignore=benchmarks --ignore=paper --ignore=unyt/_mpl_array_converter"
filterwarnings = [
    "error",
]
