name: CI

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron:  '1 0 * * *'
  workflow_dispatch:


jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
        # Test all on ubuntu, test ends on macos and windows
        include:
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.8'
          - os: macos-latest
            python-version: '3.10'
          - os: windows-latest
            python-version: '3.10'


    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip setuptools wheel setuptools_scm
          python -m pip install tox tox-pyenv coverage
      - name: Build Docs
        if: matrix.python-version == '3.8'
        run: tox -e py38-docs -vvv
      - name: Run Minimal Dependency Build
        if: matrix.python-version == '3.8'
        run: tox -e py38-dependencies
      - name: Run Minimal Dependency Version Build
        if: matrix.python-version == '3.8'
        run: tox -e py38-versions
      - name: Run Main Build
        # Run tox using the version of Python in `PATH`
        run: tox -e py -vvv
      - name: Run In-place Tests
        if: matrix.python-version == '3.8'
        run: tox -e py38-unyt-module-test-function
